# -*- coding: utf-8 -*-
"""python program

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AvdgDl84FLptrKd_SIAJHfLG7F1Ea1jj
"""

# function to check string is
# palindrome or not
def isPalindrome(s):

	# Using predefined function to
	# reverse to string print(s)
	rev = ''.join(reversed(s))

	# Checking if both string are
	# equal or not
	if (s == rev):
		return True
	return False

# main function
s = "malayalam"
ans = isPalindrome(s)

if (ans):
	print("Yes")
else:
	print("No")